### ISSUE TITLE
Internal Server Error - if invalid Python

### ISSUE THREAD

**Issue by aaronlelevier** [jpadilla/yapf-online#2]
I tried pasting in some Python from an online code snippet to format it with `yapf-online` but it resulted in a **Internal Server Error** because it was invalid Python. 

I saw in the `templates/index.html` that there's an error block, so maybe this error could be caught and displayed there. The specific exception type is `IndentationError`.

Here is a simplified case that will cause the error. Example code:

```python
x = {  'a':37,'b':42,

'c':927}

y = 'hello ''world'
z = 'hello '+'world'
a = 'hello {}'.format('world')
class foo  (     object  ):
  def f    (self   ):
    return       37*-2
def g(self, x,y=42):
      return y
      
  print('x')
  
def f  (   a ) :
  return      37-a[42-x :  y**3]
```

Trying to use `yapf` on the above code snippet locally resulted in this stack trace:

```
Traceback (most recent call last):
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/yapf/__init__.py", line 312, in run_main
    sys.exit(main(sys.argv))
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/yapf/__init__.py", line 200, in main
    verbose=args.verbose)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/yapf/__init__.py", line 250, in FormatFiles
    in_place, print_diff, verify, verbose)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/yapf/__init__.py", line 275, in _FormatFile
    logger=logging.warning)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 90, in FormatFile
    verify=verify)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 128, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 103, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 47, in parse_tokens
    for quintuple in tokens:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/tokenize.py", line 453, in generate_tokens
    ("<tokenize>", lnum, pos, line))
  File "invalid_python.py", line 14
    print('x')
    ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by jpadilla** [comment]
@aaronlelevier thanks for the report. A pull request improving this would be welcome 😃
